language: go

dist: xenial

go_import_path: git.torproject.org/pluggable-transports/snowflake.git

go:
    - 1.13.x

script:
    - test -z "$(go fmt ./...)"
    - go vet ./...
    - go test -v -race ./...
