language: go

dist: xenial

go_import_path: git.torproject.org/pluggable-transports/snowflake.git

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-5
            - gcc-5

go:
    - 1.13.x

env:
    - TRAVIS_NODE_VERSION="8" CC="gcc-5" CXX="g++-5"

before_install:
    - nvm install $TRAVIS_NODE_VERSION

install:
    - pushd proxy
    - npm install
    - popd

script:
    - test -z "$(go fmt ./...)"
    - go vet ./...
    - go test -v -race ./...
    - cd proxy
    - npm run lint
    - npm test
